// Generated by LiveScript 1.4.0
(function(){
  var jjv, ref$, assign, head, tail, omit, map, curry, times, rest, exports;
  jjv = new require('jjv')();
  ref$ = require('lodash'), assign = ref$.assign, head = ref$.head, tail = ref$.tail, omit = ref$.omit, map = ref$.map, curry = ref$.curry, times = ref$.times;
  rest = (function(){
    rest.displayName = 'rest';
    var prototype = rest.prototype, constructor = rest;
    function rest(options){
      var def;
      def = {
        root: '/api',
        permissions: {},
        log: false
      };
      this.options = assign(def, options);
    }
    prototype.add = function(resource){
      this.options.app.get(root + "/" + name, function(req, res, next){
        if (typeof this.log == 'function') {
          this.log("query " + JSON.stringify(req.query));
        }
        return model.findAll(req.query).then(function(results){
          return res.status(200).send(results).end();
        })['catch'](next);
      });
      return this.options.app.post(root + "/" + name, function(req, res, next){
        if (typeof this.log == 'function') {
          this.log("query " + JSON.stringify(req.query));
        }
        return model.findAll(req.query).then(function(results){
          return res.status(200).send(results).end();
        })['catch'](next);
      });
    };
    return rest;
  }());
  exports = rest;
}).call(this);
