// Generated by LiveScript 1.4.0
(function(){
  var ref$, assign, head, tail, omit, map, curry, times, bodyParser, rest;
  ref$ = require('lodash'), assign = ref$.assign, head = ref$.head, tail = ref$.tail, omit = ref$.omit, map = ref$.map, curry = ref$.curry, times = ref$.times;
  bodyParser = require('body-parser');
  rest = (function(){
    rest.displayName = 'rest';
    var prototype = rest.prototype, constructor = rest;
    function rest(options){
      var def;
      def = {
        root: '/api',
        permissions: {},
        log: false
      };
      this.options = assign(def, options);
      options.app.use(bodyParser.json());
    }
    prototype.add = function(resource){
      var name, ref$, root, app, log;
      name = resource.name;
      ref$ = this.options, root = ref$.root, app = ref$.app, log = ref$.log;
      app.get(root + "/" + name, function(req, res, next){
        if (typeof log == 'function') {
          log("FINDALL " + JSON.stringify(req.query));
        }
        return resource.findAll(req.query).then(function(results){
          return res.status(200).send(results).end();
        })['catch'](next);
      });
      app.get(root + "/" + name + "/:id", function(req, res, next){
        if (typeof log == 'function') {
          log("FIND " + JSON.stringify(req.params));
        }
        return resource.find(req.params.id).then(function(results){
          return res.status(200).send(results).end();
        })['catch'](next);
      });
      app.post(root + "/" + name, function(req, res, next){
        if (typeof log == 'function') {
          log("CREATE " + JSON.stringify(req.query));
        }
        return resource.findAll(req.query).then(function(results){
          return res.status(200).send(results).end();
        })['catch'](next);
      });
      return app.put(root + "/" + name + "/:id", function(req, res, next){
        if (typeof log == 'function') {
          log("UPDATE " + JSON.stringify(req.query));
        }
        return resource.update(req.params.id, req.query).then(function(results){
          return res.status(200).send(results).end();
        })['catch'](next);
      });
    };
    return rest;
  }());
  exports.rest = rest;
}).call(this);
